# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'CryptoAppiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoAppiOS
  pod 'sharedModules' , :path => '../shared/core/sharedModules'

  target 'CryptoAppiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoAppiOSUITests' do
    # Pods for testing
  end

end
