version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 4
      groups:
        android-build-tools:
          patterns:
            - "com.android.tools.build*"
        kotlin-dependencies:
          patterns:
            - "org.jetbrains.kotlinx*"
            - "org.jetbrains.kotlin*"
        app-dependencies:
          patterns:
            - "*"
